### ISSUE TITLE
Is it possible to remove Firebase authentication to post comments?

### ISSUE THREAD

**Issue by Aryagm** [soumyajit4419/Bits-0f-C0de#9]
Hi, is it possible to remove firebase and allow users to post comments without authentication?

**Comment by evan-hwang** [comment]
I don't think this project is being managed

**Comment by soumyajit4419** [comment]
> Hi, is it possible to remove firebase and allow users to post comments without authentication?

No, It would be difficult to track who commented on the posts, and deletion of the comment would be complex.
If you know any better solution do say, We can try implementing it.

**Comment by soumyajit4419** [comment]
> I don't think this project is being managed

Yes, it is being maintained. But the new features are not being added
